MAX_QUERY_LENGTH = 1000
VALID_INDEXES = ["articles", "documents", "qa_pairs", "test_collection"]
DEFAULT_TOP_K = 10
MIN_TOP_K = 1
MAX_TOP_K = 100
DEFAULT_SPARSE_WEIGHT = 0.5
DEFAULT_DENSE_WEIGHT = 0.5
DEFAULT_RERANK_WEIGHT = 0.3